# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
      runs-on: ubuntu-latest

      steps:
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'deploy@161.35.51.99'
          privateKey: ${{ secrets.SSH_KEY }}
          command: |
            cd ~/api_go_barber
            git pull origin master
            npm install
            npm run build
            npx sequelize db:migrate
            pm2 restart node-app
