# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH commmands on remote server
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/api_go_barber
            git pull origin master
            npm install
            npm run build
            npx sequelize db:migrate
            pm2 restart node-app
          host: ${{ secrets.SSH_HOST }}
          user: deploy
          key: ${{ secrets.SSH_KEY}}
          args: "-tt -vvv"
